# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :inetRouter => {
        :box_name => "centos/stream8",
        :box_version => "20230710.0",
        :vm_name => "inetRouter",
        #:public => {:ip => "10.10.10.1", :adapter => 1},
        :net => [   
                    #ip, adpter, netmask, virtualbox__intnet
                    ["127.0.0.2", 2, "255.255.255.0",  "router-net"], 
                    ["127.0.0.3", 3, "255.255.255.0",  "router-net"], 
                    ["192.168.56.10", 8, "255.255.255.0"],
                ]
    },

  :centralRouter => {
        :box_name => "centos/stream8",
        :box_version => "20230710.0",
        :vm_name => "centralRouter",
        #:public => {:ip => "10.10.10.1", :adapter => 1},
        :net => [   
                    #ip, adpter, netmask, virtualbox__intnet
                    ["127.0.0.4", 2, "255.255.255.0",  "router-net"],
                    ["127.0.0.5", 3, "255.255.255.0",  "router-net"], 
                    ["192.168.255.9", 4, "255.255.255.252",  "office1-central"],
                    ["192.168.56.11", 8, "255.255.255.0"],
                ]
    },

  :office1Router => {
        :box_name => "centos/stream8",
        :box_version => "20230710.0",
        :vm_name => "office1Router",
        :net => [
                   ["192.168.255.10", 2, "255.255.255.252",  "office1-central"],
                   ["127.0.0.6", 3, "255.255.255.0",  "vlan1"],
                   ["127.0.0.7", 4, "255.255.255.0",  "vlan1"],
                   ["127.0.0.8", 5, "255.255.255.0",  "vlan2"],
                   ["127.0.0.9", 6, "255.255.255.0",  "vlan2"],
                   ["192.168.56.20",  8, "255.255.255.0"],
                ]
    },
  
  :testClient1 => {
        :box_name => "centos/stream8",
        :box_version => "20230710.0",
        :vm_name => "testClient1",
        :net => [
                   ["127.0.0.10", 2, "255.255.255.0",  "testLAN"],
                   ["192.168.56.21",  8, "255.255.255.0"],
                ]
    },

  :testServer1 => {
        :box_name => "centos/stream8",
        :box_version => "20230710.0",
        :vm_name => "testServer1",
        :net => [
                   ["127.0.0.11", 2, "255.255.255.0",  "testLAN"],
                   ["192.168.56.22", 8, "255.255.255.0"],
                ]
    },

  :testClient2 => {
    :box_name => "debian/bullseye64",
  #  :box_version => "4.3.6",
    :vm_name => "testClient2",
    :net => [
               ["127.0.0.12", 2, "255.255.255.0",  "testLAN"],
               ["192.168.56.31",  8, "255.255.255.0"],
            ]
    },

:testServer2 => {
    :box_name => "debian/bullseye64",
 #   :box_version => "4.3.6",
    :vm_name => "testServer2",
    :net => [
               ["127.0.0.13", 2, "255.255.255.0",  "testLAN"],
               ["192.168.56.32",  8, "255.255.255.0"],
            ]
    },

}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|
   
      box.vm.box = boxconfig[:box_name]
      box.vm.box_version = boxconfig[:box_version]
      box.vm.host_name = boxconfig[:vm_name]

      box.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 2
       end

      if boxconfig[:vm_name] == "testServer2"
        box.vm.provision "ansible" do |ansible|
         ansible.playbook = "ansible/playbook.yml"
         ansible.inventory_path = "ansible/hosts"
         ansible.host_key_checking = "false"
         ansible.become = "true"
         ansible.limit = "all"
        end
      end

      boxconfig[:net].each do |ipconf|
        box.vm.network("private_network", ip: ipconf[0], adapter: ipconf[1], netmask: ipconf[2], virtualbox__intnet: ipconf[3])
      end

      if boxconfig.key?(:public)
        box.vm.network "public_network", boxconfig[:public]
      end

      box.vm.provision "shell", inline: <<-SHELL
        mkdir -p ~root/.ssh
        cp ~vagrant/.ssh/auth* ~root/.ssh
      SHELL
    end
  end
end